'use client'

import { Suspense } from 'react'
import { TableSkeleton } from '@/components/skeletons'
import { Button } from '@/components/Button'
import { HeroPattern } from '@/components/HeroPattern'
import {
  Archive,
  Download,
  Upload,
  Trash2,
  Clock,
  HardDrive,
  Loader2,
  Play,
  Calendar,
  Settings,
} from 'lucide-react'
import { useState, useEffect } from 'react'

interface Backup {
  id: string
  name: string
  type: 'full' | 'config' | 'database' | 'files'
  size: number
  createdAt: string
  status: 'completed' | 'in_progress' | 'failed'
  autoGenerated: boolean
}

interface BackupConfig {
  autoBackup: boolean
  schedule: 'daily' | 'weekly' | 'monthly'
  retentionDays: number
  maxBackups: number
  includeDatabase: boolean
  includeFiles: boolean
  includeConfig: boolean
}

function SystemBackupsContent() {
  const [backups, setBackups] = useState<Backup[]>([])
  const [config, setConfig] = useState<BackupConfig>({
    autoBackup: true,
    schedule: 'daily',
    retentionDays: 30,
    maxBackups: 10,
    includeDatabase: true,
    includeFiles: true,
    includeConfig: true,
  })
  const [loading, setLoading] = useState(true)
  const [creating, setCreating] = useState(false)

  useEffect(() => {
    const mockBackups: Backup[] = [
      {
        id: '1',
        name: 'Full Backup - 2024-01-15',
        type: 'full',
        size: 2.5 * 1024 ** 3,
        createdAt: '2024-01-15T10:00:00Z',
        status: 'completed',
        autoGenerated: true,
      },
      {
        id: '2',
        name: 'Database Backup - 2024-01-14',
        type: 'database',
        size: 850 * 1024 ** 2,
        createdAt: '2024-01-14T10:00:00Z',
        status: 'completed',
        autoGenerated: true,
      },
    ]
    setBackups(mockBackups)
    setLoading(false)
  }, [])

  const createBackup = async () => {
    setCreating(true)
    await new Promise((resolve) => setTimeout(resolve, 2000))
    setCreating(false)
  }

  const formatBytes = (bytes: number) => {
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    if (bytes === 0) return '0 Bytes'
    const i = Math.floor(Math.log(bytes) / Math.log(1024))
    return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${sizes[i]}`
  }

  if (loading) {
    return (
      <>
        <HeroPattern />
        <div className="mx-auto max-w-7xl">
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
          </div>
        </div>
      </>
    )
  }

  return (
    <>
      <HeroPattern />
      <div className="mx-auto max-w-7xl">
        <div className="mb-8">
          <div className="mb-6 flex items-center justify-between">
            <div>
              <h1 className="flex items-center gap-3 text-3xl font-bold text-zinc-900 dark:text-white">
                <Archive className="h-8 w-8 text-blue-500" />
                System Backups
              </h1>
              <p className="mt-1 text-zinc-600 dark:text-zinc-400">
                Manage backups and restore system state
              </p>
            </div>
            <Button onClick={createBackup} disabled={creating}>
              {creating ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Creating...
                </>
              ) : (
                <>
                  <Play className="mr-2 h-4 w-4" />
                  Create Backup
                </>
              )}
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
            <div className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-800">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400">
                    Total Backups
                  </p>
                  <p className="text-2xl font-bold">{backups.length}</p>
                </div>
                <Archive className="h-8 w-8 text-blue-500" />
              </div>
            </div>

            <div className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-800">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400">
                    Total Size
                  </p>
                  <p className="text-2xl font-bold">
                    {formatBytes(
                      backups.reduce((sum, b) => sum + b.size, 0),
                    )}
                  </p>
                </div>
                <HardDrive className="h-8 w-8 text-blue-500" />
              </div>
            </div>

            <div className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-800">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400">
                    Last Backup
                  </p>
                  <p className="text-2xl font-bold">
                    {backups.length > 0
                      ? new Date(backups[0].createdAt).toLocaleDateString()
                      : 'Never'}
                  </p>
                </div>
                <Clock className="h-8 w-8 text-blue-500" />
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <div className="lg:col-span-2">
            <div className="rounded-lg border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-800">
              <div className="border-b border-zinc-200 p-6 dark:border-zinc-700">
                <h3 className="text-lg font-semibold">Backup History</h3>
              </div>

              {backups.length === 0 ? (
                <div className="p-12 text-center">
                  <Archive className="mx-auto mb-4 h-12 w-12 text-zinc-400" />
                  <p className="text-zinc-600 dark:text-zinc-400">
                    No backups yet
                  </p>
                </div>
              ) : (
                <div className="divide-y divide-zinc-200 dark:divide-zinc-700">
                  {backups.map((backup) => (
                    <div key={backup.id} className="p-6">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <h4 className="mb-1 font-medium">{backup.name}</h4>
                          <div className="flex items-center gap-3 text-sm text-zinc-600 dark:text-zinc-400">
                            <span>{formatBytes(backup.size)}</span>
                            <span>
                              {new Date(backup.createdAt).toLocaleString()}
                            </span>
                            <span
                              className={`rounded px-2 py-1 text-xs ${
                                backup.status === 'completed'
                                  ? 'bg-green-100 text-green-800'
                                  : 'bg-red-100 text-red-800'
                              }`}
                            >
                              {backup.status}
                            </span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Button variant="outline" className="text-xs">
                            <Download className="h-3 w-3" />
                          </Button>
                          <Button variant="outline" className="text-xs">
                            <Upload className="h-3 w-3" />
                          </Button>
                          <Button variant="outline" className="text-xs">
                            <Trash2 className="h-3 w-3 text-red-600" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="space-y-6">
            <div className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-800">
              <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold">
                <Settings className="h-5 w-5" />
                Backup Configuration
              </h3>

              <div className="space-y-4">
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={config.autoBackup}
                    onChange={(e) =>
                      setConfig({ ...config, autoBackup: e.target.checked })
                    }
                    className="h-4 w-4 rounded text-blue-600"
                  />
                  <span className="text-sm">Enable auto-backup</span>
                </label>

                {config.autoBackup && (
                  <div className="ml-6 space-y-3">
                    <div>
                      <label className="mb-1 block text-sm font-medium">
                        Schedule
                      </label>
                      <select
                        value={config.schedule}
                        onChange={(e) =>
                          setConfig({
                            ...config,
                            schedule: e.target.value as any,
                          })
                        }
                        className="w-full rounded-lg border border-zinc-200 px-3 py-2 dark:border-zinc-700 dark:bg-zinc-900"
                      >
                        <option value="daily">Daily</option>
                        <option value="weekly">Weekly</option>
                        <option value="monthly">Monthly</option>
                      </select>
                    </div>

                    <div>
                      <label className="mb-1 block text-sm font-medium">
                        Retention (days)
                      </label>
                      <input
                        type="number"
                        min="1"
                        max="365"
                        value={config.retentionDays}
                        onChange={(e) =>
                          setConfig({
                            ...config,
                            retentionDays: parseInt(e.target.value),
                          })
                        }
                        className="w-full rounded-lg border border-zinc-200 px-3 py-2 dark:border-zinc-700 dark:bg-zinc-900"
                      />
                    </div>
                  </div>
                )}

                <Button className="w-full text-sm">Save Configuration</Button>
              </div>
            </div>

            <div className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-700 dark:bg-zinc-800">
              <h3 className="mb-4 text-lg font-semibold">Next Backup</h3>
              <div className="flex items-center gap-3">
                <Calendar className="h-5 w-5 text-blue-500" />
                <div>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400">
                    Scheduled for
                  </p>
                  <p className="font-medium">Tomorrow at 2:00 AM</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default function SystemBackupsPage() {
  return (
    <Suspense fallback={<TableSkeleton />}>
      <SystemBackupsContent />
    </Suspense>
  )
}
