import { getActiveProject } from '@/features/project-picker/project-picker'
import fs from 'fs/promises'
import { NextResponse } from 'next/server'
import path from 'path'

interface AuditItem {
  id: string
  category: string
  title: string
  description: string
  status: 'pass' | 'fail' | 'warn' | 'unknown'
  detail?: string
}

/**
 * Run the nSelf dog-food audit against the currently active project.
 *
 * Categories:
 *   - nSelf-First Doctrine  — compose is generated, no side-channel services
 *   - Doc-Sync Ritual       — SPORT exists, doc-sync workflow present
 *   - Security-Always-Free  — .env.secrets not committed, SSL enabled
 */
export async function GET() {
  try {
    const project = await getActiveProject()
    const items: AuditItem[] = []

    if (project === null) {
      items.push({
        id: 'project-missing',
        category: 'Setup',
        title: 'Active project selected',
        description: 'The audit requires a registered active project.',
        status: 'fail',
        detail: 'No active project — use the project picker to select one.',
      })
      return NextResponse.json(summarise(items))
    }

    // ---- nSelf-First Doctrine ---------------------------------------------
    items.push(await checkComposeGenerated(project.path))
    items.push(await checkNoSideChannelCompose(project.path))
    items.push(await checkEnvComputedPresent(project.path))

    // ---- Doc-Sync Ritual --------------------------------------------------
    items.push(await checkSportExists(project.path))
    items.push(await checkDocSyncWorkflow(project.path))
    items.push(await checkReadmePresent(project.path))

    // ---- Security-Always-Free --------------------------------------------
    items.push(await checkEnvSecretsIgnored(project.path))
    items.push(await checkSslCertsPresent(project.path))
    items.push(await checkGitignorePresent(project.path))

    return NextResponse.json(summarise(items))
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Audit failed.'
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}

function summarise(items: AuditItem[]) {
  const score = { pass: 0, fail: 0, warn: 0, total: items.length }
  for (const it of items) {
    if (it.status === 'pass') score.pass += 1
    else if (it.status === 'fail') score.fail += 1
    else if (it.status === 'warn') score.warn += 1
  }
  return {
    generatedAt: new Date().toISOString(),
    items,
    score,
  }
}

async function checkComposeGenerated(root: string): Promise<AuditItem> {
  try {
    const raw = await fs.readFile(
      path.join(root, 'docker-compose.yml'),
      'utf-8',
    )
    const ok = raw.includes('GENERATED BY nself build')
    return {
      id: 'compose-generated',
      category: 'nSelf-First Doctrine',
      title: 'docker-compose.yml is CLI-generated',
      description:
        'The compose file must carry the GENERATED BY nself build header.',
      status: ok ? 'pass' : 'warn',
      detail: ok ? undefined : 'Header missing — may be hand-edited.',
    }
  } catch {
    return {
      id: 'compose-generated',
      category: 'nSelf-First Doctrine',
      title: 'docker-compose.yml is CLI-generated',
      description:
        'The compose file must carry the GENERATED BY nself build header.',
      status: 'warn',
      detail: 'No docker-compose.yml yet — run `nself build`.',
    }
  }
}

async function checkNoSideChannelCompose(root: string): Promise<AuditItem> {
  const sideFiles = ['docker-compose.prod.yml', 'docker-compose.custom.yml']
  const found: string[] = []
  for (const f of sideFiles) {
    try {
      await fs.access(path.join(root, f))
      found.push(f)
    } catch {
      // ignore
    }
  }
  return {
    id: 'no-side-channel',
    category: 'nSelf-First Doctrine',
    title: 'No side-channel compose files',
    description:
      'All services go through nself build. No hand-maintained compose variants.',
    status: found.length === 0 ? 'pass' : 'warn',
    detail: found.length === 0 ? undefined : `Found: ${found.join(', ')}`,
  }
}

async function checkEnvComputedPresent(root: string): Promise<AuditItem> {
  try {
    await fs.access(path.join(root, '.env.computed'))
    return {
      id: 'env-computed',
      category: 'nSelf-First Doctrine',
      title: '.env.computed generated',
      description: 'orchestration.sh has written the resolved env file.',
      status: 'pass',
    }
  } catch {
    return {
      id: 'env-computed',
      category: 'nSelf-First Doctrine',
      title: '.env.computed generated',
      description: 'orchestration.sh has written the resolved env file.',
      status: 'warn',
      detail: 'Run `nself build` to generate.',
    }
  }
}

async function checkSportExists(root: string): Promise<AuditItem> {
  try {
    const stat = await fs.stat(path.join(root, '.claude/docs/sport'))
    return {
      id: 'sport-exists',
      category: 'Doc-Sync Ritual',
      title: 'SPORT directory present',
      description: '.claude/docs/sport/ holds canonical reference facts.',
      status: stat.isDirectory() ? 'pass' : 'fail',
    }
  } catch {
    return {
      id: 'sport-exists',
      category: 'Doc-Sync Ritual',
      title: 'SPORT directory present',
      description: '.claude/docs/sport/ holds canonical reference facts.',
      status: 'warn',
      detail:
        'Not present — nSelf PPI-level only; ignore if this is a consumer project.',
    }
  }
}

async function checkDocSyncWorkflow(root: string): Promise<AuditItem> {
  try {
    await fs.access(path.join(root, '.github/workflows/doc-sync.yml'))
    return {
      id: 'doc-sync-workflow',
      category: 'Doc-Sync Ritual',
      title: 'doc-sync CI workflow present',
      description: '.github/workflows/doc-sync.yml enforces doc drift gate.',
      status: 'pass',
    }
  } catch {
    return {
      id: 'doc-sync-workflow',
      category: 'Doc-Sync Ritual',
      title: 'doc-sync CI workflow present',
      description: '.github/workflows/doc-sync.yml enforces doc drift gate.',
      status: 'warn',
      detail: 'Missing — doc drift may slip through CI.',
    }
  }
}

async function checkReadmePresent(root: string): Promise<AuditItem> {
  try {
    await fs.access(path.join(root, 'README.md'))
    return {
      id: 'readme',
      category: 'Doc-Sync Ritual',
      title: 'README.md present',
      description: 'Public surface documentation exists.',
      status: 'pass',
    }
  } catch {
    return {
      id: 'readme',
      category: 'Doc-Sync Ritual',
      title: 'README.md present',
      description: 'Public surface documentation exists.',
      status: 'fail',
    }
  }
}

async function checkEnvSecretsIgnored(root: string): Promise<AuditItem> {
  try {
    const raw = await fs.readFile(path.join(root, '.gitignore'), 'utf-8')
    const ok = /\.env(\.secrets|\.\*)?/.test(raw)
    return {
      id: 'env-secrets-ignored',
      category: 'Security-Always-Free',
      title: '.env.secrets is gitignored',
      description: 'Secrets must never be committed.',
      status: ok ? 'pass' : 'fail',
    }
  } catch {
    return {
      id: 'env-secrets-ignored',
      category: 'Security-Always-Free',
      title: '.env.secrets is gitignored',
      description: 'Secrets must never be committed.',
      status: 'fail',
      detail: 'No .gitignore found.',
    }
  }
}

async function checkSslCertsPresent(root: string): Promise<AuditItem> {
  const candidates = ['ssl/certs', 'nginx/ssl', '.ssl']
  for (const c of candidates) {
    try {
      await fs.access(path.join(root, c))
      return {
        id: 'ssl-certs',
        category: 'Security-Always-Free',
        title: 'SSL certificates present',
        description: 'Local dev TLS is enabled.',
        status: 'pass',
        detail: `Found at ${c}`,
      }
    } catch {
      // keep trying
    }
  }
  return {
    id: 'ssl-certs',
    category: 'Security-Always-Free',
    title: 'SSL certificates present',
    description: 'Local dev TLS is enabled.',
    status: 'warn',
    detail: 'No SSL directory found — run `nself ssl` to generate.',
  }
}

async function checkGitignorePresent(root: string): Promise<AuditItem> {
  try {
    await fs.access(path.join(root, '.gitignore'))
    return {
      id: 'gitignore',
      category: 'Security-Always-Free',
      title: '.gitignore present',
      description: 'Base hygiene in place.',
      status: 'pass',
    }
  } catch {
    return {
      id: 'gitignore',
      category: 'Security-Always-Free',
      title: '.gitignore present',
      description: 'Base hygiene in place.',
      status: 'fail',
    }
  }
}
