/**
 * Vibe-Code Generate API
 * POST /api/vibe/generate — submit a feature request prompt for generation
 *
 * Proxies to vibe_api CS_2 (port 8002). Returns a VibeGeneration object.
 * The vibe_api runs VibeAgent which calls specialist sub-agents:
 *   MigrationAgent, PermissionsAgent, UIAgent
 */

import { requireAuth } from '@/lib/require-auth'
import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

const VIBE_ENABLED = process.env.NSELF_VIBE_ENABLED === 'true'
const VIBE_API_PORT = process.env.NSELF_VIBE_PORT ?? '8003'
const VIBE_API_BASE = `http://127.0.0.1:${VIBE_API_PORT}`
const MAX_PROMPT_TOKENS = parseInt(
  process.env.NSELF_VIBE_MAX_PROMPT_TOKENS ?? '16000',
  10,
)

const GenerateSchema = z.object({
  session_id: z.string().min(1),
  prompt: z.string().min(1).max(4000),
})

// Rate limit: max 1 generate-in-flight per session (tracked by session_id)
const inflightSessions = new Set<string>()

export async function POST(request: NextRequest): Promise<NextResponse> {
  const authError = await requireAuth(request)
  if (authError) return authError

  if (!VIBE_ENABLED) {
    return NextResponse.json(
      { error: 'Vibe-Code is disabled. Set NSELF_VIBE_ENABLED=true.' },
      { status: 503 },
    )
  }

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const parsed = GenerateSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: 'Invalid request', details: parsed.error.flatten() },
      { status: 400 },
    )
  }

  const { session_id, prompt } = parsed.data

  // Prompt injection guard: strip dangerous patterns before forwarding
  const sanitizedPrompt = sanitizePrompt(prompt)

  if (inflightSessions.has(session_id)) {
    return NextResponse.json(
      { error: 'A generation is already in progress for this session.' },
      { status: 429 },
    )
  }

  inflightSessions.add(session_id)

  try {
    let generationData: object

    try {
      const vibeRes = await fetch(`${VIBE_API_BASE}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id,
          prompt: sanitizedPrompt,
          max_tokens: MAX_PROMPT_TOKENS,
          ai_provider: process.env.NSELF_VIBE_AI_PROVIDER ?? 'claw-ai',
          ui_framework: process.env.NSELF_VIBE_UI_FRAMEWORK ?? 'react',
        }),
        signal: AbortSignal.timeout(35000), // 35s: spec says 30s p50
      })

      if (!vibeRes.ok) {
        const errBody = (await vibeRes.json()) as { error?: string }
        throw new Error(errBody.error ?? `vibe_api error: ${vibeRes.status}`)
      }

      generationData = (await vibeRes.json()) as object
    } catch (fetchErr) {
      // vibe_api not running — return stub generation for UI development
      if (
        (fetchErr as Error).message.includes('ECONNREFUSED') ||
        (fetchErr as Error).message.includes('fetch failed')
      ) {
        generationData = buildStubGeneration(session_id, sanitizedPrompt)
      } else {
        throw fetchErr
      }
    }

    return NextResponse.json(generationData)
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Generation failed'
    return NextResponse.json({ error: message }, { status: 500 })
  } finally {
    inflightSessions.delete(session_id)
  }
}

/**
 * Sanitize prompt to prevent injection of dangerous DDL.
 * The MigrationAgent also validates output, but this is defense-in-depth.
 */
function sanitizePrompt(prompt: string): string {
  // Strip common SQL injection patterns from the prompt text
  // We don't block legitimate mentions of SQL keywords in feature descriptions
  // Just strip explicit executable injection attempts
  return prompt
    .replace(
      /;\s*(DROP|TRUNCATE|DELETE\s+FROM\s+\w+\s*;|ALTER\s+TABLE)/gi,
      '; [BLOCKED DDL]',
    )
    .trim()
}

/**
 * Stub generation for when vibe_api CS_2 is not yet running.
 * Returns a realistic shape so the UI can be developed/tested.
 */
function buildStubGeneration(session_id: string, prompt: string): object {
  const feature = prompt.slice(0, 50)
  return {
    id: `gen-${Date.now().toString(36)}`,
    session_id,
    created_at: new Date().toISOString(),
    prompt,
    migration_sql: `-- Generated by VibeAgent (stub mode)\n-- Feature: ${feature}\n\nCREATE TABLE IF NOT EXISTS np_stub_feature (\n    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    user_id    UUID,\n    body       TEXT NOT NULL\n);\n\nCREATE INDEX np_stub_feature_user_id_idx ON np_stub_feature (user_id);\n`,
    permissions_json: {
      type: 'table',
      table: { schema: 'public', name: 'np_stub_feature' },
      role: 'user',
      select: {
        columns: ['id', 'created_at', 'user_id', 'body'],
        filter: { user_id: { _eq: 'X-Hasura-User-Id' } },
      },
      insert: {
        columns: ['user_id', 'body'],
        check: { user_id: { _eq: 'X-Hasura-User-Id' } },
      },
      delete: {
        filter: { user_id: { _eq: 'X-Hasura-User-Id' } },
      },
    },
    ui_files: {
      'StubFeature.tsx': `import { useState } from 'react'\n\nexport function StubFeature() {\n  const [items, setItems] = useState<string[]>([])\n\n  return (\n    <div className="p-4">\n      <h2 className="text-lg font-semibold">Stub Feature</h2>\n      {/* Generated by VibeAgent — vibe_api stub mode */}\n      <p className="text-sm text-gray-500 mt-2">Connect vibe_api CS_2 for full generation.</p>\n    </div>\n  )\n}\n`,
    },
    status: 'done',
    applied_at: null,
    ai_model: 'stub',
    tokens_used: 0,
    _stub: true,
  }
}
